[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "breastcancer"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.11.1",
    "flwr-datasets[vision]>=0.3.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
    "scikit-learn==1.5.2",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flower"

[tool.flwr.app.components]
serverapp = "breastcancer.server_app:app"
clientapp = "breastcancer.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 10
fraction_fit = 1.0
fraction_evaluate = 1.0
min_fit_clients = 5
min_evaluate_clients = 5
min_available_clients = 5
local-epochs = 1

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10

[tool.flwr.federations.local-deployment]
address = "127.0.0.1:9093"
insecure = true
